### PR TITLE
Install more recent versions of OMERO.py

### PR DESCRIPTION
**Pull request by sbesson**
This relaxes the pinning of the OMERO.py version to allow the Prometheus exporter to keep connecting to OMERO.server instances with the latest security protocol enhancements. Without this change, the createSession() will fail Connection reset by peer and the metrics endpoint returns a `Connection refused`

This was discovered in the context of https://github.com/ome/omero-certificates/pull/38#pullrequestreview-1626402135. After running the latest `omero certificates` command, the monitoring endpoint started failing for this instance. Locally, this got resolved by running

```
[sbesson@test120-omeroreadonly-2 prometheus-omero-tools]$ sudo /opt/prometheus-omero-tools/venv3/bin/pip install -U omero-py
[sbesson@test120-omeroreadonly-2 prometheus-omero-tools]$ sudo systemctl restart prometheus-omero-exporter
```

A patch release of the role will be required in order for the monitoring of next IDR deployments to remain functional with `omero-certificates 0.3.0`. Note also the Molecule CI is failing and might need to be fixed separately or as a prerequisite @pwalczysko and @khaledk2

### CODE REVIEW

**Comment by sbesson** [comment]
I think OMERO.py 5.13.0 is the minimal version required in order to connect against a server set-up with the latest `omero-certificates` and d882eda updates the role accordingly.
A secondary advantage of increasing the minimal version is that the new version of the role will also force an OMERO.py upgrade of existing deployments created with an older version of this role.

**Comment by khaledk2** [comment]
The Elasticsearch nodes did not run correctly, I have checked that and found out that the CA file was not written to the mapped folder, so I have added a pause for 1 minute and tested that and it should work fine now. 
@sbesson I have stopped all the containers then deleted the stopped containers and created folders, could you please re-run the playbook again?

**Comment by pwalczysko** [comment]
Build is green on https://github.com/ome/ansible-role-omero-prometheus-exporter/pull/10

**Comment by pwalczysko** [comment]
Maybe rebase to make build pass ?

**Comment by pwalczysko** [comment]
The test is now failing, was not successful in trying to fix it. I think the service is not running.

**Comment by sbesson** [comment]
@pwalczysko  I was also confused how your https://github.com/ome/ansible-role-omero-prometheus-exporter/pull/10 ended up passing the builds while the actions on https://github.com/ome/prod-playbooks have been consistently failing since the release of `omero-certificates 0.3.0`.

After investigation, turns out the Molecule test was not setting up a server with self-signed certificates. https://github.com/ome/ansible-role-omero-prometheus-exporter/pull/9/commits/22a9e3a2e0d3eea6a2a062b2654c03396aac4efe adds the corresponding option and fixes the CI build and [194789e](https://github.com/ome/ansible-role-omero-prometheus-exporter/pull/9/commits/194789ecd8f46a4826a3ad563c7bd2bad40d66ff) adds a note to the README.

**Review by pwalczysko — APPROVED** [review]

**Comment by pwalczysko** [comment]
Could we maybe merge this please ? I suppose merging it would fix the tests in https://github.com/ome/prod-playbooks/pull/373 and thus allow the https://github.com/ome/prod-playbooks/pull/373 to be merged. Or do I get it wrong ?

cc @sbesson @jburel

**Comment by sbesson** [comment]
Yes I believe this is the root issue of the failing monitoring tests. We'll also need this reviewed and released to consume it in the upcoming IDR deployments

**Review by jburel — APPROVED** [review]

**Comment by pwalczysko** [comment]
> Yes I believe this is the root issue of the failing monitoring tests. We'll also need this reviewed and released to consume it in the upcoming IDR deployments

@sbesson Re-run the tests after this PR got merged, but still failing https://github.com/ome/prod-playbooks/pull/373 - what am I getting wrong please ?

**Comment by sbesson** [comment]
Has this been released?

**Comment by jburel** [comment]
just tagged 0.3.4

**Comment by pwalczysko** [comment]
```
Run ome/action-ansible-galaxy-publish@main
  with:
    galaxy-api-key: ***
Run ansible-galaxy role import --api-key *** ${GITHUB_REPOSITORY%/*} ${GITHUB_REPOSITORY#*/}
  ansible-galaxy role import --api-key *** ${GITHUB_REPOSITORY%/*} ${GITHUB_REPOSITORY#*/}
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
ERROR! Error when finding available api versions from default (https://galaxy.ansible.com/) (HTTP Code: 403, Message: Forbidden)
Error: Process completed with exit code 1.
```

https://github.com/ome/ansible-role-omero-prometheus-exporter/actions/runs/6432255572/job/17467049347

**Pull request merged**
